version: '3.7'
services:
  ollama:
    image: ollama/ollama:latest
    restart: unless-stopped
    volumes:
      - ./data:/root/.ollama
    ports:
      - '11435:11434'
    container_name: jaroflyes-ollama_ollama_1

  app_proxy:
    image: umbrellabs/proxy:latest   # ← problema aqui
    restart: unless-stopped
    environment:
      APP_HOST: ollama
      APP_PORT: 11434
      PROXY_AUTH_ADD: 'false'
    container_name: jaroflyes-ollama_app_proxy_1
